benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 64x16x2, ici_size_range: 2048, sharding_strategy: 1x16x1, op_dimension: 1, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 8x8x32, ici_size_range: 2048, sharding_strategy: 1x1x32, op_dimension: 1, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 8x32x8, ici_size_range: 2048, sharding_strategy: 1x32x1, op_dimension: 1, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 32x8x8, ici_size_range: 2048, sharding_strategy: 32x1x1, op_dimension: 1, num_runs: 5}
  trace_dir: ../microbenchmarks/all_gather_1d
  csv_path: ../microbenchmarks/all_gather_1d
  xlml_metrics_dir: ../microbenchmarks/all_gather_1d
  xla_dump_dir: ../microbenchmarks/all_gather_1d/hlo_graphs
