benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "8x8x32", ici_size_range: 128, sharding_strategy: "4x4x16", op_dimension: 3, num_runs: 5} # Non Parallel Replica Groups
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "1024x2", ici_size_range: 1024, sharding_strategy: "1024x1", op_dimension: 3, num_runs: 5} # Parallel Replica Groups
  trace_dir: "../microbenchmarks/all_gather_3d"
  csv_path: "../microbenchmarks/all_gather_3d"
  xlml_metrics_dir: "../microbenchmarks/all_gather_3d"
  xla_dump_dir: "../microbenchmarks/all_gather_3d/hlo_graphs"