benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "8x128x2", ici_size_range: 1024, sharding_strategy: "1x128x1", op_dimension: 2, num_runs: 5} # Parallel Replica Groups
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "8x256", ici_size_range: 1024, sharding_strategy: "1x256", op_dimension: 2, num_runs: 5}  # Non Parallel Replica Groups
  trace_dir: "../microbenchmarks/all_reduce_2d"
  csv_path: "../microbenchmarks/all_reduce_2d"
  xlml_metrics_dir: "../microbenchmarks/all_reduce_2d"
  xla_dump_dir: "../microbenchmarks/all_reduce_2d/hlo_graphs"