benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 8x128x2, ici_size_range: 2048, sharding_strategy: 1x128x1, op_dimension: 2, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 8x8x32, ici_size_range: 2048, sharding_strategy: 1x8x32, op_dimension: 2, num_runs: 5}
  trace_dir: ../microbenchmarks/psum_2d
  csv_path: ../microbenchmarks/psum_2d
  xlml_metrics_dir: ../microbenchmarks/psum_2d
  xla_dump_dir: ../microbenchmarks/psum_2d/hlo_graphs
