benchmarks:
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "8x8x32", ici_size_range: 1024, sharding_strategy: "1x1x16", op_dimension: 1,  num_runs: 5} # Non-Parallel Replica
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "64x16x2", ici_size_range: 1024, sharding_strategy: "1x16x1", op_dimension: 1,  num_runs: 5} # Parallel Replica
  trace_dir: "../microbenchmarks/reduce_scatter_1d"
  csv_path: "../microbenchmarks/reduce_scatter_1d"
  xlml_metrics_dir: "../microbenchmarks/reduce_scatter_1d"
  xla_dump_dir: "../microbenchmarks/reduce_scatter_1d/hlo_graphs"