benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 4}, dtype: "float32",  mesh_shape: "2x2x2", ici_size_range: 8, sharding_strategy: "2x2x1", op_dimension: 1, num_runs: 5} # Parallel Replica
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 4}, dtype: "float32",  mesh_shape: "1x8", ici_size_range: 8, sharding_strategy: "1x8", op_dimension: 1, num_runs: 5} # Non-Parallel Replica
  
  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_gather"
  csv_path: "../microbenchmarks/all_gather"
  xlml_metrics_dir: "../microbenchmarks/all_gather"
  xla_dump_dir: "../microbenchmarks/all_gather/hlo_graphs"