benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 4x16x2, ici_size_range: 128, sharding_strategy: 1x16x1, op_dimension: 2, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 4x4x8, ici_size_range: 128, sharding_strategy: 1x4x8, op_dimension: 2, num_runs: 5}
  trace_dir: ../microbenchmarks/psum_2d
  csv_path: ../microbenchmarks/psum_2d
  xlml_metrics_dir: ../microbenchmarks/psum_2d
  xla_dump_dir: ../microbenchmarks/psum_2d/hlo_graphs
