benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "1x4x1", op_dimension: 1, num_runs: 5} # Parallel Replica
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4x8", ici_size_range: 128, sharding_strategy: "1x1x8", op_dimension: 1,  num_runs: 5} # Non-Parallel Replica Z
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "4x8x4", ici_size_range: 128, sharding_strategy: "1x8x1", op_dimension: 1,  num_runs: 5} # Non-Parallel Replica Y
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "8x4x4", ici_size_range: 128, sharding_strategy: "8x1x1", op_dimension: 1,  num_runs: 5} # Non-Parallel Replica X
  trace_dir: "../microbenchmarks/all_gather_1d"
  csv_path: "../microbenchmarks/all_gather_1d"
  xlml_metrics_dir: "../microbenchmarks/all_gather_1d"
  xla_dump_dir: "../microbenchmarks/all_gather_1d/hlo_graphs"