benchmarks:
- benchmark_name: host_device_smart_chunking
  num_runs: 20
  benchmark_sweep_params:
  - {
      data_size_mib_list: [1, 16, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]
    }
  csv_path: "../microbenchmarks/host_device_smart_chunking"
  trace_dir: "../microbenchmarks/host_device_smart_chunking/trace"
