benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 64x8x2, ici_size_range: 1024, sharding_strategy: 1x8x1, op_dimension: 1, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: float32, mesh_shape: 8x8x16, ici_size_range: 1024, sharding_strategy: 1x1x16, op_dimension: 1, num_runs: 5}
  trace_dir: ../microbenchmarks/psum_1d
  csv_path: ../microbenchmarks/psum_1d
  xlml_metrics_dir: ../microbenchmarks/psum_1d
  xla_dump_dir: ../microbenchmarks/psum_1d/hlo_graphs
