benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 131072, multiplier: 2}, dtype: "float32",  mesh_shape: "8x128", ici_size_range: 1024, sharding_strategy: "1x128", op_dimension: 2, num_runs: 5} # Non Parallel Replica
  trace_dir: "../microbenchmarks/all_to_all_2d"
  csv_path: "../microbenchmarks/all_to_all_2d"
  xlml_metrics_dir: "../microbenchmarks/all_to_all_2d"
  xla_dump_dir: "../microbenchmarks/all_to_all_2d/hlo_graphs"